### ISSUE TITLE
NPE when enabling StorageESP

### ISSUE THREAD

**Issue by omninope** [kami-blue/client#1820]
**Describe the bug**
Enabling StorageESP causes a NPE immediately.

**To Reproduce**
1. Build KAMI Blue on commit 6de259097a780f15ca55b24022cf083373655e08;
2. In game enable StorageESP;
3. Crash.

**Expected behavior**
Don't crash.

**Debug info**
Link for the crash report: [https://pastebin.com/5B4UZK27](https://pastebin.com/5B4UZK27).

**Additional context / media**
Probably not necessary.

**Comment by l1ving** [comment]
I thought we fixed that :/

**Comment by Xiaro** [comment]
Might be fixed in 3103974. need testing.

**Comment by omninope** [comment]
Build it on commit 3b7b5bf36dabee767ec63ac0a72cebf254099a08 and tested again, and the crash still happens, the log is the same too.
I tested it more carefully and the issue only happens when enabling rendering for entities and for block entities at the same time, separate they work fine.

**Comment by omninope** [comment]
Just realized my description may not have been clear enough, what I meant is it's possible to use StorageESP rendering for chests, ender chests, hoppers, droppers and furnaces, also it's possible to use rendering for item frames and minecarts but you cannot combine them, like if you enable rendering for minecarts and chests it will crash.
